# Generated by Django 4.1.4 on 2024-03-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_doctor_patienttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttime',
            name='user',
            field=models.ManyToManyField(to='polls.doctor'),
        ),
    ]
