# Generated by Django 4.1.4 on 2024-03-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_patienttime_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienttime',
            name='user',
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.ManyToManyField(to='polls.polluser'),
        ),
    ]
