# Generated by Django 4.1.4 on 2024-03-29 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_patienttime_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienttime',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='doctor',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
