# Generated by Django 4.1.4 on 2024-03-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_patienttime_pub_date_doctor_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='pub_date',
            field=models.CharField(max_length=50),
        ),
    ]
