# Generated by Django 4.1.4 on 2024-03-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_doctor_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
