# Generated by Django 4.1.4 on 2024-03-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_datechoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datechoice',
            name='date',
        ),
    ]
