# Generated by Django 4.1.4 on 2024-03-29 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_delete_datechoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('pub_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.doctor')),
            ],
        ),
    ]
