# Generated by Django 4.1.4 on 2024-03-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='pub_date',
            new_name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.CharField(default='Default Text', max_length=50),
        ),
    ]
